/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.beanloaf.leaftools;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import net.beanloaf.leaftools.gui.GuiLightaltargui;
import net.beanloaf.leaftools.gui.GuiInfusergui;
import net.beanloaf.leaftools.gui.GuiGuidetitle;
import net.beanloaf.leaftools.gui.GuiGuidepage9;
import net.beanloaf.leaftools.gui.GuiGuidepage8;
import net.beanloaf.leaftools.gui.GuiGuidepage7;
import net.beanloaf.leaftools.gui.GuiGuidepage6;
import net.beanloaf.leaftools.gui.GuiGuidepage5;
import net.beanloaf.leaftools.gui.GuiGuidepage4;
import net.beanloaf.leaftools.gui.GuiGuidepage3;
import net.beanloaf.leaftools.gui.GuiGuidepage21;
import net.beanloaf.leaftools.gui.GuiGuidepage20;
import net.beanloaf.leaftools.gui.GuiGuidepage2;
import net.beanloaf.leaftools.gui.GuiGuidepage19;
import net.beanloaf.leaftools.gui.GuiGuidepage18;
import net.beanloaf.leaftools.gui.GuiGuidepage17;
import net.beanloaf.leaftools.gui.GuiGuidepage16;
import net.beanloaf.leaftools.gui.GuiGuidepage15;
import net.beanloaf.leaftools.gui.GuiGuidepage14;
import net.beanloaf.leaftools.gui.GuiGuidepage13;
import net.beanloaf.leaftools.gui.GuiGuidepage12;
import net.beanloaf.leaftools.gui.GuiGuidepage11;
import net.beanloaf.leaftools.gui.GuiGuidepage10;
import net.beanloaf.leaftools.gui.GuiGuidepage1;
import net.beanloaf.leaftools.gui.GuiGuideTOC;
import net.beanloaf.leaftools.gui.GuiDustholdergui;
import net.beanloaf.leaftools.gui.GuiDustextractorgui;
import net.beanloaf.leaftools.gui.GuiAngelicswordgui;
import net.beanloaf.leaftools.gui.GuiAngelicshovelgui;
import net.beanloaf.leaftools.gui.GuiAngelicpickaxegui;
import net.beanloaf.leaftools.gui.GuiAngelicaxegui;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ElementsLeafToolsMod implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsLeafToolsMod() {
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsLeafToolsMod.ModElement.class)
					elements.add((ElementsLeafToolsMod.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsLeafToolsMod.ModElement::initElements);
		this.addNetworkMessage(LeafToolsModVariables.WorldSavedDataSyncMessageHandler.class, LeafToolsModVariables.WorldSavedDataSyncMessage.class,
				Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = LeafToolsModVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = LeafToolsModVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				LeafToolsMod.PACKET_HANDLER.sendTo(new LeafToolsModVariables.WorldSavedDataSyncMessage(0, mapdata), (EntityPlayerMP) event.player);
			if (worlddata != null)
				LeafToolsMod.PACKET_HANDLER.sendTo(new LeafToolsModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = LeafToolsModVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				LeafToolsMod.PACKET_HANDLER.sendTo(new LeafToolsModVariables.WorldSavedDataSyncMessage(1, worlddata), (EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			LeafToolsMod.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiInfusergui.GUIID)
				return new GuiInfusergui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiDustextractorgui.GUIID)
				return new GuiDustextractorgui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiDustholdergui.GUIID)
				return new GuiDustholdergui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiLightaltargui.GUIID)
				return new GuiLightaltargui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuideTOC.GUIID)
				return new GuiGuideTOC.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage3.GUIID)
				return new GuiGuidepage3.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidetitle.GUIID)
				return new GuiGuidetitle.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage1.GUIID)
				return new GuiGuidepage1.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage2.GUIID)
				return new GuiGuidepage2.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage4.GUIID)
				return new GuiGuidepage4.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage5.GUIID)
				return new GuiGuidepage5.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage6.GUIID)
				return new GuiGuidepage6.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage7.GUIID)
				return new GuiGuidepage7.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage8.GUIID)
				return new GuiGuidepage8.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage9.GUIID)
				return new GuiGuidepage9.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage10.GUIID)
				return new GuiGuidepage10.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage11.GUIID)
				return new GuiGuidepage11.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage12.GUIID)
				return new GuiGuidepage12.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage13.GUIID)
				return new GuiGuidepage13.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage14.GUIID)
				return new GuiGuidepage14.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage15.GUIID)
				return new GuiGuidepage15.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage16.GUIID)
				return new GuiGuidepage16.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage17.GUIID)
				return new GuiGuidepage17.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage18.GUIID)
				return new GuiGuidepage18.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage19.GUIID)
				return new GuiGuidepage19.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage20.GUIID)
				return new GuiGuidepage20.GuiContainerMod(world, x, y, z, player);
			if (id == GuiGuidepage21.GUIID)
				return new GuiGuidepage21.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAngelicpickaxegui.GUIID)
				return new GuiAngelicpickaxegui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAngelicswordgui.GUIID)
				return new GuiAngelicswordgui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAngelicaxegui.GUIID)
				return new GuiAngelicaxegui.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAngelicshovelgui.GUIID)
				return new GuiAngelicshovelgui.GuiContainerMod(world, x, y, z, player);
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiInfusergui.GUIID)
				return new GuiInfusergui.GuiWindow(world, x, y, z, player);
			if (id == GuiDustextractorgui.GUIID)
				return new GuiDustextractorgui.GuiWindow(world, x, y, z, player);
			if (id == GuiDustholdergui.GUIID)
				return new GuiDustholdergui.GuiWindow(world, x, y, z, player);
			if (id == GuiLightaltargui.GUIID)
				return new GuiLightaltargui.GuiWindow(world, x, y, z, player);
			if (id == GuiGuideTOC.GUIID)
				return new GuiGuideTOC.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage3.GUIID)
				return new GuiGuidepage3.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidetitle.GUIID)
				return new GuiGuidetitle.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage1.GUIID)
				return new GuiGuidepage1.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage2.GUIID)
				return new GuiGuidepage2.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage4.GUIID)
				return new GuiGuidepage4.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage5.GUIID)
				return new GuiGuidepage5.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage6.GUIID)
				return new GuiGuidepage6.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage7.GUIID)
				return new GuiGuidepage7.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage8.GUIID)
				return new GuiGuidepage8.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage9.GUIID)
				return new GuiGuidepage9.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage10.GUIID)
				return new GuiGuidepage10.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage11.GUIID)
				return new GuiGuidepage11.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage12.GUIID)
				return new GuiGuidepage12.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage13.GUIID)
				return new GuiGuidepage13.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage14.GUIID)
				return new GuiGuidepage14.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage15.GUIID)
				return new GuiGuidepage15.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage16.GUIID)
				return new GuiGuidepage16.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage17.GUIID)
				return new GuiGuidepage17.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage18.GUIID)
				return new GuiGuidepage18.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage19.GUIID)
				return new GuiGuidepage19.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage20.GUIID)
				return new GuiGuidepage20.GuiWindow(world, x, y, z, player);
			if (id == GuiGuidepage21.GUIID)
				return new GuiGuidepage21.GuiWindow(world, x, y, z, player);
			if (id == GuiAngelicpickaxegui.GUIID)
				return new GuiAngelicpickaxegui.GuiWindow(world, x, y, z, player);
			if (id == GuiAngelicswordgui.GUIID)
				return new GuiAngelicswordgui.GuiWindow(world, x, y, z, player);
			if (id == GuiAngelicaxegui.GUIID)
				return new GuiAngelicaxegui.GuiWindow(world, x, y, z, player);
			if (id == GuiAngelicshovelgui.GUIID)
				return new GuiAngelicshovelgui.GuiWindow(world, x, y, z, player);
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsLeafToolsMod elements;
		protected final int sortid;
		public ModElement(ElementsLeafToolsMod elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
